## HAJRA BIBI
## 2k24/TYCS/2

In [2]:
!pip install numpy

In [8]:
import numpy as np
# Create a 2x3 matrix
matrix1 = np.array([[1,2,3],
                   [4,5,6]])

# Create a 3x3 matrix
matrix2 = np.array([[7,8,9],
                   [10,11,12],
                   [13,14,15]])

#Create a matrix of zeros with shape 2x2
zeros_matrix = np.zeros((2,2))

#Create a matrix of ones with shape 3x4
ones_matrix = np.ones((3,4))

#Create an identity matrix of size 3x3
identity_matrix = np.eye(3)

#create a diagonal matrix from a list
diagonal_matrix = np.diag([1,2,3,4])

#create a random matrix with shape 2x2
random_matrix = np.random.rand(2,2)

#display the matrices

print("Matrix 1:\n", matrix1)
print("\nMatrix 2 :\n", matrix2)
print("\nZeros Matrix :\n", zeros_matrix)
print("\nOnes Matrix :\n", ones_matrix)
print("\nIdentity Matrix :\n", identity_matrix)   
print("\nDiagonal Matrix :\n", diagonal_matrix)  
print("\nRandom Matrix :\n", random_matrix)      
      
      





Matrix 1:
 [[1 2 3]
 [4 5 6]]

Matrix 2 :
 [[ 7  8  9]
 [10 11 12]
 [13 14 15]]

Zeros Matrix :
 [[0. 0.]
 [0. 0.]]

Ones Matrix :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity Matrix :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Diagonal Matrix :
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Random Matrix :
 [[0.128559   0.16926922]
 [0.17106879 0.56947103]]
